### ISSUE TITLE
Source debugging is not possible

### ISSUE THREAD

**Issue by luigiberrettini** [luigiberrettini/NLog.Targets.Syslog#162]
Using [SourceLink](https://github.com/dotnet/sourcelink) it is possible for NuGet package users to debug NLog.Targets.Syslog source code

**Comment by luigiberrettini** [comment]
At the moment publication of symbols [is not supported](https://github.com/appveyor/ci/issues/2753) by AppVeyor and can only be done with a workaround by means of a [secure variable](https://www.appveyor.com/docs/build-configuration/#secure-variables) containing the NuGet API key:
```yaml
environment:
  NuGet_api_key:
    secure: <encrypt_value>

after_deploy:
  - ps : Get-ChildItem .\tools\artifacts\*.snupkg | % { dotnet nuget push $_.FullName -s https://api.nuget.org/v3/index.json -k $env:NuGet_api_key }
```
